% Author: Charles ZHU
% --
%

init_env;

GRACE_PERIOD = 60;

get_next_item_f = @(ls_plan, t_comp, ...
    data_queue, id_ap, simu_time, current_rate, history) ...
    get_next_item_strict(ls_plan, t_comp, ...
        data_queue, id_ap, simu_time, current_rate, history, GRACE_PERIOD);

fprintf('Running simulation with sample workspace: tiny_ds_size.mat\n\n');
[act_r, est_r, act_t_up] = run( ...
    'sample/tiny_ds_size.mat', ...
    @simu_t_move_0, ...
    ds_wait_f, op_wait_f, AP_AVERAGE_WAIT_TIME, ...
    download_f, upload_f, ...
    change_rates_f, ...
    get_next_item_f); %#ok<*ASGLU>

fprintf('Estimated weighted overall utility: %.4f\n', est_r);
fprintf('Actual weighted overall utility: %.4f\n', act_r);
fprintf('\n');

fprintf('Running simulation with sample workspace: tiny_op_number.mat\n\n');
[act_r, est_r, act_t_up] = run( ...
    'sample/tiny_op_number.mat', ...
    @simu_t_move_0, ...
    ds_wait_f, op_wait_f, AP_AVERAGE_WAIT_TIME, ...
    download_f, upload_f, ...
    change_rates_f, ...
    get_next_item_f);

fprintf('Estimated weighted overall utility: %.4f\n', est_r);
fprintf('Actual weighted overall utility: %.4f\n', act_r);
fprintf('\n');

fprintf('Running simulation with sample workspace: tiny_op_sigma.mat\n\n');
[act_r, est_r, act_t_up] = run( ...
    'sample/tiny_op_sigma.mat', ...
    @simu_t_move_0, ...
    ds_wait_f, op_wait_f, AP_AVERAGE_WAIT_TIME, ...
    download_f, upload_f, ...
    change_rates_f, ...
    get_next_item_f);

fprintf('Estimated weighted overall utility: %.4f\n', est_r);
fprintf('Actual weighted overall utility: %.4f\n', act_r);
fprintf('\n');
fprintf('Done\n');
