function [ret] = get_next_item_fixed(grace_p)
ret = @(ls_plan, t_comp, data_queue, id_ap, simu_time, current_rate, ...
    history) ...
    get_next_item_fixed_k( ...
        ls_plan, t_comp, data_queue, id_ap, simu_time, current_rate, ...
        history, grace_p);

end

