function [ret] = run_dy_move_2(basic_wait, ...
    ds_average_retry_time, ...
    ap_average_wait_time, ...
    ds_trans_overhead, ap_trans_overhead, ...
    t_move_f, ...
    get_next_item_f)
ret = @(matrix_file) ...
    run_3(matrix_file, ...
        t_move_f, ...
        simu_t_wait_exp_fixed(basic_wait, ds_average_retry_time), ...
        simu_t_wait_exp_average(basic_wait), ...
        ap_average_wait_time, ...
        simu_t_download_overhead(ds_trans_overhead), ...
        simu_t_upload_overhead(ap_trans_overhead), ...
        @simu_change_rates_0, @simu_change_data_0, ...
        get_next_item_f);

end

