function [ret] = run_co_data_3(t_wait, ...
    ds_data_change_f, ...
    get_next_item_f)
ret = @(matrix_file) ...
    run_3(matrix_file, ...
        @simu_t_move_0, ...
        @simu_t_wait_0, ...
        @simu_t_wait_0, ...
        t_wait, ...
        @simu_t_download_0, ...
        @simu_t_upload_0, ...
        @simu_change_rates_0, ds_data_change_f, ...
        get_next_item_f);

end

