% Author: Charles ZHU
% --
%

clear
clc

fprintf('Running simulation with sample workspace: tiny_ds_size.mat\n');
[act_r, est_r, act_t_up] = run( ...
    'sample/tiny_ds_size.mat', ...
    @simu_t_move_0, ...
    @simu_t_wait_0, @simu_t_wait_0, 12, ...
    @simu_t_download_0, @simu_t_upload_0, ...
    @simu_change_rates_0, ...
    @get_next_item_0); %#ok<*ASGLU>

fprintf('Estimated weighted overall utility: %.4f\n', est_r);
fprintf('Actual weighted overall utility: %.4f\n', act_r);
fprintf('\n');

fprintf('Running simulation with sample workspace: tiny_op_number.mat\n');
[act_r, est_r, act_t_up] = run( ...
    'sample/tiny_op_number.mat', ...
    @simu_t_move_0, ...
    @simu_t_wait_0, @simu_t_wait_0, 12, ...
    @simu_t_download_0, @simu_t_upload_0, ...
    @simu_change_rates_0, ...
    @get_next_item_0);

fprintf('Estimated weighted overall utility: %.4f\n', est_r);
fprintf('Actual weighted overall utility: %.4f\n', act_r);
fprintf('\n');

fprintf('Running simulation with sample workspace: tiny_op_sigma.mat\n');
[act_r, est_r, act_t_up] = run( ...
    'sample/tiny_op_sigma.mat', ...
    @simu_t_move_0, ...
    @simu_t_wait_0, @simu_t_wait_0, 12, ...
    @simu_t_download_0, @simu_t_upload_0, ...
    @simu_change_rates_0, ...
    @get_next_item_0);

fprintf('Estimated weighted overall utility: %.4f\n', est_r);
fprintf('Actual weighted overall utility: %.4f\n', act_r);
fprintf('\n');
fprintf('Done\n');
